"use client"

import { ColumnDef } from "@tanstack/react-table"
import { ArrowRight, Eye, X, BookOpen, CalendarDays, Tag, Hash, Mail, IdCard, Library } from "lucide-react"
import { useState } from "react"

import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/ui/alert-dialog"

import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog"

import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Separator } from "@/components/ui/separator"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"

import { Admission } from "@/types/admission"
import { CURRICULA } from "@/lib/dummy/curricula"
import { COURSES } from "@/lib/dummy/courses"

// ─── Status badge ─────────────────────────────────────────────────────────────
function StatusBadge({ status }: { status: Admission["status"] }) {
  const map: Record<Admission["status"], { label: string; className: string }> = {
    Pending: {
      label: "Pending",
      className:
        "bg-yellow-100 text-yellow-800 border-yellow-200 dark:bg-yellow-900/30 dark:text-yellow-400 dark:border-yellow-800",
    },
    Approved: {
      label: "Approved",
      className:
        "bg-green-100 text-green-800 border-green-200 dark:bg-green-900/30 dark:text-green-400 dark:border-green-800",
    },
    Rejected: {
      label: "Rejected",
      className:
        "bg-red-100 text-red-800 border-red-200 dark:bg-red-900/30 dark:text-red-400 dark:border-red-800",
    },
  }

  const { label, className } = map[status]
  return (
    <Badge variant="outline" className={`font-medium ${className}`}>
      {label}
    </Badge>
  )
}

// ─── Step indicator ───────────────────────────────────────────────────────────
const STEPS = ["Enroll", "Confirm"]

function StepIndicator({ current }: { current: number }) {
  return (
    <div className="flex items-center">
      {STEPS.map((label, i) => {
        const done = i < current
        const active = i === current
        return (
          <div key={label} className="flex items-center">
            <div className="flex flex-col items-center gap-1">
              <div
                className={`flex size-7 items-center justify-center rounded-full border-2 text-xs font-semibold transition-colors
                  ${done ? "border-primary bg-primary text-primary-foreground" : ""}
                  ${active ? "border-primary bg-background text-primary" : ""}
                  ${!done && !active ? "border-muted-foreground/30 bg-background text-muted-foreground/50" : ""}
                `}
              >
                {done ? "✓" : i + 1}
              </div>
              <span
                className={`text-[10px] font-medium leading-none whitespace-nowrap
                  ${active ? "text-primary" : "text-muted-foreground/60"}
                `}
              >
                {label}
              </span>
            </div>
            {i < STEPS.length - 1 && (
              <div
                className={`mb-4 h-px w-16 transition-colors ${done ? "bg-primary" : "bg-muted-foreground/20"}`}
              />
            )}
          </div>
        )
      })}
    </div>
  )
}

// ─── Next Step dialog ─────────────────────────────────────────────────────────
function NextStepDialog({
  applicant,
  open,
  onOpenChange,
}: {
  applicant: Admission
  open: boolean
  onOpenChange: (open: boolean) => void
}) {
  const [step, setStep] = useState(0)
  const [selectedCourse, setSelectedCourse] = useState("")
  const [selectedCurriculum, setSelectedCurriculum] = useState("")

  // Autogenerated student ID (read-only)
  const generatedStudentId = `${new Date().getFullYear()}-${applicant.id.padStart(5, "0")}`

  const availableCurricula = selectedCourse ? (CURRICULA[selectedCourse] ?? []) : []

  function handleClose() {
    onOpenChange(false)
    setTimeout(() => {
      setStep(0)
      setSelectedCourse("")
      setSelectedCurriculum("")
    }, 200)
  }

  function handleNext() {
    if (step < STEPS.length - 1) setStep((s) => s + 1)
  }

  function handleBack() {
    if (step > 0) setStep((s) => s - 1)
  }

  function handleConfirm() {
    // TODO: wire to your API
    console.log("Enroll applicant", {
      applicantId: applicant.id,
      studentId: generatedStudentId,
      course: selectedCourse,
      curriculum: selectedCurriculum,
    })
    handleClose()
  }

  const canNext = step === 0 && !!selectedCourse && !!selectedCurriculum

  return (
    <Dialog open={open} onOpenChange={handleClose}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle className="text-base font-semibold">
          </DialogTitle>
        </DialogHeader>

        {/* Step indicator */}
        <div className="flex justify-center pt-1">
          <StepIndicator current={step} />
        </div>

        {/* Applicant summary strip */}
        <div className="flex items-center gap-3 rounded-lg border bg-muted/40 px-3 py-2">
          <div className="flex size-9 shrink-0 items-center justify-center rounded-full bg-muted text-sm font-semibold text-muted-foreground select-none">
            {applicant.fullName
              .split(" ")
              .slice(0, 2)
              .map((n) => n[0])
              .join("")
              .toUpperCase()}
          </div>
          <div className="min-w-0">
            <p className="truncate text-sm font-medium">{applicant.fullName}</p>
            <p className="truncate text-xs text-muted-foreground">
              {applicant.id} · {applicant.admissionType}
            </p>
          </div>
        </div>

        <Separator />

        {/* ── Step 0: Enroll ── */}
        {step === 0 && (
          <div className="grid gap-4 py-1">
            <div className="grid gap-1.5">
              <Label htmlFor="student-id" className="flex items-center gap-1.5">
                <IdCard className="size-3.5 text-muted-foreground" />
                Student ID
                <span className="ml-1 text-[10px] text-muted-foreground">(autogenerated)</span>
              </Label>
              <Input
                id="student-id"
                value={generatedStudentId}
                disabled
                className="text-muted-foreground"
              />
            </div>

            {/* Course */}
            <div className="grid gap-1.5">
              <Label className="flex items-center gap-1.5">
                <BookOpen className="size-3.5 text-muted-foreground" />
                Course
              </Label>
              <Select
                value={selectedCourse}
                onValueChange={(val) => {
                  setSelectedCourse(val)
                  setSelectedCurriculum("")
                }}
              >
                <SelectTrigger className="w-full">
                  <SelectValue placeholder="Select a course" />
                </SelectTrigger>
                <SelectContent>
                  {COURSES.map((c) => (
                    <SelectItem key={c.value} value={c.value}>
                      {c.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            {/* Curriculum */}
            <div className="grid gap-1.5">
              <Label className="flex items-center gap-1.5">
                <Library className="size-3.5 text-muted-foreground" />
                Curriculum
              </Label>
              <Select
                value={selectedCurriculum}
                onValueChange={setSelectedCurriculum}
                disabled={!selectedCourse}
              >
                <SelectTrigger className="w-full">
                  <SelectValue
                    placeholder={
                      selectedCourse ? "Select a curriculum" : "Select a course first"
                    }
                  />
                </SelectTrigger>
                <SelectContent>
                  {availableCurricula.map((c) => (
                    <SelectItem key={c.value} value={c.value}>
                      {c.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>
        )}

        {/* ── Step 1: Confirm ── */}
        {step === 1 && (
          <div className="grid gap-3 py-1">
            <p className="text-sm text-muted-foreground">
              Review the details before confirming enrollment.
            </p>
            <dl className="grid gap-2 rounded-lg border bg-muted/40 p-3 text-sm">
              {[
                { label: "Applicant", value: applicant.fullName },
                { label: "Student ID", value: generatedStudentId },
                {
                  label: "Course",
                  value: COURSES.find((c) => c.value === selectedCourse)?.label ?? "—",
                },
                {
                  label: "Curriculum",
                  value:
                    availableCurricula.find((c) => c.value === selectedCurriculum)?.label ?? "—",
                },
              ].map(({ label, value }) => (
                <div
                  key={label}
                  className="grid grid-cols-[120px_1fr] items-start gap-2"
                >
                  <dt className="text-muted-foreground">{label}</dt>
                  <dd className="font-medium">{value}</dd>
                </div>
              ))}
            </dl>
          </div>
        )}

        <DialogFooter className="flex-row justify-between gap-2 sm:justify-between">
          <Button
            variant="outline"
            size="sm"
            onClick={handleBack}
            disabled={step === 0}
          >
            Back
          </Button>
          <div className="flex gap-2">
            {step < STEPS.length - 1 ? (
              <Button size="sm" onClick={handleNext} disabled={!canNext}>
                Next
                <ArrowRight className="ml-1.5 size-3.5" />
              </Button>
            ) : (
              <Button size="sm" onClick={handleConfirm}>
                Confirm Enrollment
              </Button>
            )}
          </div>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}

// ─── View dialog ──────────────────────────────────────────────────────────────

function ViewDialog({
  applicant,
  open,
  onOpenChange,
}: {
  applicant: Admission
  open: boolean
  onOpenChange: (open: boolean) => void
}) {
  const fields = [
    {
      icon: <Hash className="size-4 text-muted-foreground" />,
      label: "Applicant No.",
      value: applicant.id,
    },
    {
      icon: <BookOpen className="size-4 text-muted-foreground" />,
      label: "Course",
      value: applicant.course,
    },
    {
      icon: <Tag className="size-4 text-muted-foreground" />,
      label: "Admission Type",
      value: applicant.admissionType,
    },
    {
      icon: <CalendarDays className="size-4 text-muted-foreground" />,
      label: "Date Applied",
      value: applicant.appliedAt,
    },
  ]

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle className="text-base font-semibold">
            Applicant Details
          </DialogTitle>
        </DialogHeader>

        <Separator />

        {/* Avatar / name hero */}
        <div className="flex items-center gap-3 py-1">
          <div className="flex size-11 shrink-0 items-center justify-center rounded-full bg-muted text-lg font-semibold text-muted-foreground select-none">
            {applicant.fullName
              .split(" ")
              .slice(0, 2)
              .map((n) => n[0])
              .join("")
              .toUpperCase()}
          </div>
          <div className="min-w-0">
            <p className="truncate font-medium leading-tight">{applicant.fullName}</p>
          
          </div>
          <div className="ml-auto shrink-0">
            <StatusBadge status={applicant.status} />
          </div>
        </div>

        <Separator />

        <dl className="grid gap-3 py-1">
          {fields.map((field) => (
            <div
              key={field.label}
              className="grid grid-cols-[1fr_auto] items-start gap-2 text-sm"
            >
              <dt className="flex items-center gap-2 text-muted-foreground">
                {field.icon}
                {field.label}
              </dt>
              <dd className="text-right font-medium">{field.value}</dd>
            </div>
          ))}
        </dl>
      </DialogContent>
    </Dialog>
  )
}

// ─── Actions cell ─────────────────────────────────────────────────────────────
function ActionsCell({ applicant }: { applicant: Admission }) {
  const [viewOpen, setViewOpen] = useState(false)
  const [nextStepOpen, setNextStepOpen] = useState(false)

  return (
    <>
      <div className="flex items-center justify-center gap-1">
        {/* View */}
        <Button
          size="sm"
          variant="ghost"
          className="h-8 gap-1.5 px-2 text-xs"
          onClick={() => setViewOpen(true)}
        >
          <Eye className="size-3.5" />
          View
        </Button>

        {/* Next Step */}
        <Button
          size="sm"
          variant="ghost"
          className="h-8 gap-1.5 px-2 text-xs text-blue-600 hover:text-blue-700"
          onClick={() => setNextStepOpen(true)}
        >
          Enroll
          <ArrowRight className="size-3.5" />
        </Button>

        {/* Reject */}
        <AlertDialog>
          <AlertDialogTrigger asChild>
            <Button
              size="sm"
              variant="ghost"
              className="h-8 gap-1.5 px-2 text-xs text-red-500 hover:text-red-600"
            >
              <X className="size-3.5" />
              Reject
            </Button>
          </AlertDialogTrigger>

          <AlertDialogContent>
            <AlertDialogHeader>
              <AlertDialogTitle>Reject Application?</AlertDialogTitle>
              <AlertDialogDescription>
                This action cannot be undone.
              </AlertDialogDescription>
            </AlertDialogHeader>

            <AlertDialogFooter>
              <AlertDialogCancel>Cancel</AlertDialogCancel>
              <AlertDialogAction
                className="bg-red-500 text-white hover:bg-red-600"
                onClick={() => console.log("Reject", applicant.id)}
              >
                Reject
              </AlertDialogAction>
            </AlertDialogFooter>
          </AlertDialogContent>
        </AlertDialog>
      </div>

      <ViewDialog applicant={applicant} open={viewOpen} onOpenChange={setViewOpen} />
      <NextStepDialog applicant={applicant} open={nextStepOpen} onOpenChange={setNextStepOpen} />
    </>
  )
}

// ─── Column definitions ───────────────────────────────────────────────────────
export const columns: ColumnDef<Admission>[] = [
  { accessorKey: "id", header: "Applicant No." },
  { accessorKey: "fullName", header: "Full Name" },
  { accessorKey: "course", header: "Course" },
  { accessorKey: "admissionType", header: "Admission Type" },
  { accessorKey: "admissionFor", header: "Admission For" },
  { accessorKey: "appliedAt", header: "Date Applied" },
  {
    accessorKey: "status",
    header: "Status",
    cell: ({ row }) => <StatusBadge status={row.original.status} />,
  },
  {
    id: "actions",
    header: () => <div className="text-center">Actions</div>,
    cell: ({ row }) => <ActionsCell applicant={row.original} />,
  },
]