import type { Metadata } from "next";
import { Geist, Geist_Mono, Figtree } from "next/font/google";
// import "./globals.css";
import "@/app/globals.css";
import { cn } from "@/lib/utils";


import Navbar from "@/components/navbar";
import Sidebar from "@/components/appsidebar";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import { SidebarProvider } from "@/components/ui/sidebar";
import { cookies } from "next/headers";

const figtree = Figtree({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// use asyn here 2
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  //await to store sidebar state 1
  const cookieStore = await cookies()
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true"

  return (
    <html lang="en" className={cn("font-sans", figtree.variable)} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}

      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange>

            <SidebarProvider defaultOpen={defaultOpen}>
              <Sidebar />
               <main className="w-full">
                  <Navbar />
                    <div className="px-4">{children}

                    </div>
                </main>
            </SidebarProvider>
      </ThemeProvider>
      </body>
    </html>
  );
}
