import { User } from "@/types/admin/user"

export const users: User[] = [
  { id: "NSC26-0001", fullname: "Juan Dela Cruz", email: "juan.delacruz@nsci.edu.ph", user_type: "faculty" },
  { id: "NSC26-0002", fullname: "Maria Clara Reyes", email: "maria.reyes@nsci.edu.ph", user_type: "college_registrar" },
  { id: "NSC26-0003", fullname: "Pedro Penduko", email: "pedro.penduko@nsci.edu.ph", user_type: "college_student" },
  { id: "NSC26-0004", fullname: "Anna Patricia Bautista", email: "anna.bautista@nsci.edu.ph", user_type: "college_student" },
  { id: "NSC26-0005", fullname: "Mark Anthony Garcia", email: "mark.garcia@nsci.edu.ph", user_type: "faculty" },
  { id: "NSC26-0006", fullname: "Luisita Gomez", email: "luisita.gomez@nsci.edu.ph", user_type: "college_student" },
  { id: "NSC26-0007", fullname: "Roberto Navarro", email: "roberto.navarro@nsci.edu.ph", user_type: "college_student" },
  { id: "NSC26-0008", fullname: "Elena Fernandez", email: "elena.fernandez@nsci.edu.ph", user_type: "faculty" },
  { id: "NSC26-0009", fullname: "Carlos Mendoza", email: "carlos.mendoza@nsci.edu.ph", user_type: "college_student" },
  { id: "NSC26-0010", fullname: "Sofia Villanueva", email: "sofia.villanueva@nsci.edu.ph", user_type: "college_student" },
  { id: "NSC26-0011", fullname: "Miguel Torres", email: "miguel.torres@nsci.edu.ph", user_type: "college_student" },
  { id: "NSC26-0012", fullname: "Isabela Flores", email: "isabela.flores@nsci.edu.ph", user_type: "faculty" },
  { id: "NSC26-0013", fullname: "Ramon Castro", email: "ramon.castro@nsci.edu.ph", user_type: "college_student" },
  { id: "NSC26-0014", fullname: "Carmen Santiago", email: "carmen.santiago@nsci.edu.ph", user_type: "college_student" },
  { id: "NSC26-0015", fullname: "Ricardo Dantes", email: "ricardo.dantes@nsci.edu.ph", user_type: "college_student" },
  { id: "NSC26-0016", fullname: "Teresa Aquino", email: "teresa.aquino@nsci.edu.ph", user_type: "faculty" },
  { id: "NSC26-0017", fullname: "Vicente Lim", email: "vicente.lim@nsci.edu.ph", user_type: "college_student" },
  { id: "NSC26-0018", fullname: "Rosa Rosal", email: "rosa.rosal@nsci.edu.ph", user_type: "college_student" },
  { id: "NSC26-0019", fullname: "Fernando Poe", email: "fernando.poe@nsci.edu.ph", user_type: "college_student" },
  { id: "NSC26-0020", fullname: "Gloria Romero", email: "gloria.romero@nsci.edu.ph", user_type: "faculty" },
  { id: "NSC26-0021", fullname: "Antonio Luna", email: "antonio.luna@nsci.edu.ph", user_type: "college_student" },
  { id: "NSC26-0022", fullname: "Emilio Jacinto", email: "emilio.jacinto@nsci.edu.ph", user_type: "college_student" },
  { id: "NSC26-0023", fullname: "Gabriela Silang", email: "gabriela.silang@nsci.edu.ph", user_type: "college_student" },
  { id: "NSC26-0024", fullname: "Apolinario Mabini", email: "apolinario.mabini@nsci.edu.ph", user_type: "faculty" },
  { id: "NSC26-0025", fullname: "Melchora Aquino", email: "melchora.aquino@nsci.edu.ph", user_type: "college_registrar" },
  { id: "NSC26-0026", fullname: "Diego Silang", email: "diego.silang@nsci.edu.ph", user_type: "college_student" },
  { id: "NSC26-0027", fullname: "Leonor Rivera", email: "leonor.rivera@nsci.edu.ph", user_type: "college_student" },
]